# The default settings can be found at:
# `/opt/homebrew/Cellar/latexindent/<ver>/libexec/bin`
# (replace `<ver>` with the actual version).

indentRules:
  item: "    "

defaultIndent: "    "

noAdditionalIndent:
  doublespace: 1
  multicols: 1

indentAfterItems:
  itemize: 0
  itemize*: 0
  enumerate: 0
  enumerate*: 0
  ditemize: 0
  denumerate: 0

lookForAlignDelims:
  matrix:
    alignDoubleBackSlash: 0
  matrix*:
    alignDoubleBackSlash: 0
  pmatrix:
    alignDoubleBackSlash: 0
  pmatrix*:
    alignDoubleBackSlash: 0
  bmatrix:
    alignDoubleBackSlash: 0
  bmatrix*:
    alignDoubleBackSlash: 0
  Bmatrix:
    alignDoubleBackSlash: 0
  Bmatrix*:
    alignDoubleBackSlash: 0
  vmatrix:
    alignDoubleBackSlash: 0
  vmatrix*:
    alignDoubleBackSlash: 0
  Vmatrix:
    alignDoubleBackSlash: 0
  Vmatrix*:
    alignDoubleBackSlash: 0
  game:
    alignDoubleBackSlash: 0
  align:
    alignDoubleBackSlash: 0
  align*:
    alignDoubleBackSlash: 0
  alignat:
    alignDoubleBackSlash: 0
  alignat*:
    alignDoubleBackSlash: 0
  aligned:
    alignDoubleBackSlash: 0
  aligned*:
    alignDoubleBackSlash: 0
  alignedat:
    alignDoubleBackSlash: 0
  alignedat*:
    alignDoubleBackSlash: 0
  cases:
    alignDoubleBackSlash: 0
  dcases:
    alignDoubleBackSlash: 0
  tabular:
    alignDoubleBackSlash: 0
  tblr:
    alignDoubleBackSlash: 0
