# The default setting can be find at
# `/usr/local/Cellar/latexindent/<ver>/libexec/bin`
# (replace `<ver>` with the actual version)

indentRules:
  item: "    "

defaultIndent: "    "

noAdditionalIndent:
  doublespace: 1
  multicols: 1
