# The default settings can be found at:
# `/opt/homebrew/Cellar/latexindent/<ver>/libexec/bin`
# (replace `<ver>` with the actual version).

indentRules:
  item: "    "

defaultIndent: "    "

noAdditionalIndent:
  doublespace: 1
  multicols: 1

indentAfterItems:
  itemize: 0
  itemize*: 0
  enumerate: 0
  enumerate*: 0
  ditemize: 0
  denumerate: 0

lookForAlignDelims:
  matrix*: 1
  pmatrix*: 1
  bmatrix*: 1
  Bmatrix*: 1
  vmatrix*: 1
  Vmatrix*: 1
  game: 1
  tblr:
    alignDoubleBackSlash: 0 #
    # Ideally, this should be set for all align-like environments.
