# The default setting can be find at
# `/usr/local/Cellar/latexindent/<ver>/libexec/bin`
# (replace `<ver>` with the actual version)

indentRules:
  item: "    "

defaultIndent: "    "

noAdditionalIndent:
  doublespace: 1
  multicols: 1

lookForAlignDelims:
  matrix*: 1
  pmatrix*: 1
  bmatrix*: 1
  Bmatrix*: 1
  vmatrix*: 1
  Vmatrix*: 1
  game: 1
  tblr: 0

verbatimEnvironments:
  Verbatim: 1
